<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [1]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [10]:
%%sql
SELECT

EXTRACT(YEAR FROM orderdate) AS order_year,
EXTRACT(MONTH FROM orderdate) AS order_month,
SUM(s.quantity*s.netprice*s.exchangerate) AS net_revenue,
COUNT(DISTINCT(s.customerkey)) AS Customers

FROM sales s

GROUP BY order_month,order_year
ORDER BY order_month,order_year

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

112 rows affected.

    order_year order_month  net_revenue  customers
0         2015           1    384092.66        200
1         2016           1    835484.26        323
2         2017           1    996797.10        332
3         2018           1   1675202.32        586
4         2019           1   3082448.20       1093
..         ...         ...          ...        ...
107       2019          12   2696740.22       1003
108       2020          12    524808.49        241
109       2021          12   3643597.36       1435
110       2022          12   4238010.83       1960
111       2023          12   2928550.93       1484

[112 rows x 4 columns]

In [18]:
%%sql
SELECT
p.categoryname,
s.orderdate,
EXTRACT (YEAR FROM orderdate) AS order_year,
EXTRACT (YEAR FROM CURRENT_DATE) AS current_year,
EXTRACT (YEAR FROM CURRENT_DATE) -5 AS minus_5_year,
SUM(s.quantity*s.netprice*s.exchangerate) AS net_revenue

FROM sales s
LEFT JOIN product p ON s.productkey = p.productkey
WHERE
  EXTRACT (YEAR FROM orderdate) >= EXTRACT (YEAR FROM CURRENT_DATE) -5
GROUP BY s.orderdate,p.productkey
ORDER BY s.orderdate,p.productkey

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

117278 rows affected.

,categoryname,orderdate,order_year,current_year,minus_5_year,net_revenue
0,Audio,2020-01-01,2020,2025,2020,475.58
1,Audio,2020-01-01,2020,2025,2020,552.02
2,Audio,2020-01-01,2020,2025,2020,176.54
3,Audio,2020-01-01,2020,2025,2020,221.33
4,Audio,2020-01-01,2020,2025,2020,296.84
...,...,...,...,...,...,...
117273,Home Appliances,2024-04-20,2024,2025,2020,285.83
117274,Cell phones,2024-04-20,2024,2025,2020,25.33
117275,Cell phones,2024-04-20,2024,2025,2020,22.24
117276,Cell phones,2024-04-20,2024,2025,2020,113.86
117277,Cell phones,2024-04-20,2024,2025,2020,106.16